"""add customization change and text

Revision ID: 04afa25de6aa
Revises: 1c0065991dcd
Create Date: 2025-05-02 19:59:31.065615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04afa25de6aa'
down_revision: Union[str, None] = '1c0065991dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('customization_text', sa.String(length=1000), nullable=True))
    op.add_column('cards', sa.Column('customization_changes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'customization_changes')
    op.drop_column('cards', 'customization_text')
    # ### end Alembic commands ###
