"""change duplicated field

Revision ID: 14cceaae8253
Revises: e98d5c525ac4
Create Date: 2025-05-04 03:35:46.992224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14cceaae8253"
down_revision: Union[str, None] = "e98d5c525ac4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE cards ALTER COLUMN duplicated_by TYPE JSON USING duplicated_by::json"
    )
    op.execute(
        "ALTER TABLE cards ALTER COLUMN alternated_by TYPE JSON USING alternated_by::json"
    )
    # ### end Alembic commands ###
    op.alter_column(
        "cards",
        "alternated_by",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cards",
        "alternated_by",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "cards",
        "duplicated_by",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
