"""Add field for encounter cards

Revision ID: 15649f598b2d
Revises: 46d81505ac13
Create Date: 2025-08-28 21:41:38.198084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15649f598b2d'
down_revision: Union[str, None] = '46d81505ac13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('encounter_code', sa.String(length=50), nullable=True))
    op.add_column('cards', sa.Column('encounter_name', sa.String(length=200), nullable=True))
    op.add_column('cards', sa.Column('encounter_position', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('shroud', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('clues', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('victory', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('spoilers', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'spoilers')
    op.drop_column('cards', 'victory')
    op.drop_column('cards', 'clues')
    op.drop_column('cards', 'shroud')
    op.drop_column('cards', 'encounter_position')
    op.drop_column('cards', 'encounter_name')
    op.drop_column('cards', 'encounter_code')
    # ### end Alembic commands ###
