"""add customization option

Revision ID: 1c0065991dcd
Revises: 39072061769e
Create Date: 2025-05-02 17:50:06.388104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0065991dcd'
down_revision: Union[str, None] = '39072061769e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('customization_options', sa.JSON(), nullable=True))
    op.drop_column('taboos', 'taboo_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taboos', sa.Column('taboo_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('cards', 'customization_options')
    # ### end Alembic commands ###
