"""update taboo table

Revision ID: 1d8069667cc5
Revises: cfffda0e6569
Create Date: 2025-05-02 16:45:19.223763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d8069667cc5'
down_revision: Union[str, None] = 'cfffda0e6569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_taboos',
    sa.Column('card_code', sa.String(length=50), nullable=True),
    sa.Column('taboo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_code'], ['cards.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taboo_id'], ['taboos.id'], ondelete='CASCADE')
    )
    op.drop_constraint('taboos_id_key', 'taboos', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('taboos_id_key', 'taboos', ['id'])
    op.drop_table('card_taboos')
    # ### end Alembic commands ###
