"""change foreign key lazy to subquery

Revision ID: 1ebdc2fd1a23
Revises: 0ff5f3fa7f48
Create Date: 2025-08-31 01:37:37.729544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebdc2fd1a23'
down_revision: Union[str, None] = '0ff5f3fa7f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
