"""add field

Revision ID: 39072061769e
Revises: 01cf92a6ad90
Create Date: 2025-05-02 17:10:40.983885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39072061769e'
down_revision: Union[str, None] = '01cf92a6ad90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taboos', sa.Column('taboo_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taboos', 'taboo_code')
    # ### end Alembic commands ###
