"""Create Table

Revision ID: 3e7cc632825a
Revises: 
Create Date: 2025-04-24 20:29:31.869326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7cc632825a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('real_name', sa.String(length=200), nullable=True),
    sa.Column('subname', sa.String(length=200), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('real_text', sa.String(length=200), nullable=False),
    sa.Column('type_code', sa.String(length=50), nullable=False),
    sa.Column('type_name', sa.String(length=200), nullable=False),
    sa.Column('faction_code', sa.String(length=50), nullable=False),
    sa.Column('faction_name', sa.String(length=200), nullable=False),
    sa.Column('alternate_of_code', sa.String(length=50), nullable=False),
    sa.Column('alternate_of_name', sa.String(length=200), nullable=False),
    sa.Column('pack_code', sa.String(length=50), nullable=False),
    sa.Column('pack_name', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_unique', sa.Boolean(), nullable=False),
    sa.Column('exceptional', sa.Boolean(), nullable=False),
    sa.Column('myriad', sa.Boolean(), nullable=False),
    sa.Column('permanent', sa.Boolean(), nullable=False),
    sa.Column('double_sided', sa.Boolean(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.Column('octgn_id', sa.String(length=50), nullable=False),
    sa.Column('flavor', sa.String(length=200), nullable=False),
    sa.Column('back_flavor', sa.String(length=200), nullable=False),
    sa.Column('back_text', sa.String(length=200), nullable=False),
    sa.Column('deck_limit', sa.Integer(), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('health_per_investigator', sa.Integer(), nullable=False),
    sa.Column('sanity', sa.Integer(), nullable=False),
    sa.Column('skill_willpower', sa.Integer(), nullable=False),
    sa.Column('skill_intellect', sa.Integer(), nullable=False),
    sa.Column('skill_combat', sa.Integer(), nullable=False),
    sa.Column('skill_agility', sa.Integer(), nullable=False),
    sa.Column('skill_wild', sa.Integer(), nullable=False),
    sa.Column('real_slot', sa.String(length=50), nullable=False),
    sa.Column('illustrator', sa.String(length=200), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=True),
    sa.Column('deck_requirements', sa.JSON(), nullable=True),
    sa.Column('deck_options', sa.JSON(), nullable=True),
    sa.Column('imagesrc', sa.String(length=200), nullable=False),
    sa.Column('backimagesrc', sa.String(length=200), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', 'id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('traits',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name', 'id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('card_traits',
    sa.Column('card_code', sa.String(length=50), nullable=False),
    sa.Column('trait_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['card_code'], ['cards.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trait_name'], ['traits.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_code', 'trait_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_traits')
    op.drop_table('traits')
    op.drop_table('cards')
    # ### end Alembic commands ###
