"""add encounter table

Revision ID: 4bca2ed6d3dc
Revises: 62762393c8ec
Create Date: 2025-09-02 20:04:28.946371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bca2ed6d3dc'
down_revision: Union[str, None] = '62762393c8ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounter_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pack_code', sa.String(length=50), nullable=True),
    sa.Column('pack_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    postgresql_with_oids=False
    )
    op.create_index(op.f('ix_encounter_sets_code'), 'encounter_sets', ['code'], unique=True)
    op.create_table('card_encounter_sets',
    sa.Column('card_code', sa.String(length=50), nullable=False),
    sa.Column('encounter_set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_code'], ['cards.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encounter_set_id'], ['encounter_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_code', 'encounter_set_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_encounter_sets')
    op.drop_index(op.f('ix_encounter_sets_code'), table_name='encounter_sets')
    op.drop_table('encounter_sets')
    # ### end Alembic commands ###
