"""Add foreign key for Card

Revision ID: 5e9f99b78169
Revises: 15649f598b2d
Create Date: 2025-08-29 23:22:07.906162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e9f99b78169'
down_revision: Union[str, None] = '15649f598b2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('linked_to_code', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'cards', 'cards', ['linked_to_code'], ['code'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'linked_to_code')
    # ### end Alembic commands ###
