"""add enemy fields

Revision ID: 6019b46b9e7d
Revises: 4bca2ed6d3dc
Create Date: 2025-09-03 14:50:18.825211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6019b46b9e7d'
down_revision: Union[str, None] = '4bca2ed6d3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('enemy_damage', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('enemy_evade', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('enemy_fight', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('enemy_horror', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'enemy_horror')
    op.drop_column('cards', 'enemy_fight')
    op.drop_column('cards', 'enemy_evade')
    op.drop_column('cards', 'enemy_damage')
    # ### end Alembic commands ###
