"""add bonded cards table

Revision ID: 62762393c8ec
Revises: 1ebdc2fd1a23
Create Date: 2025-08-31 13:10:39.785702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62762393c8ec'
down_revision: Union[str, None] = '1ebdc2fd1a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonded_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_code', sa.String(length=50), nullable=False),
    sa.Column('bonded_card_code', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bonded_card_code'], ['cards.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['card_code'], ['cards.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bonded_cards')
    # ### end Alembic commands ###
