"""add taboo code

Revision ID: 976fa39ccd42
Revises: 14cceaae8253
Create Date: 2025-05-04 03:46:53.489681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976fa39ccd42'
down_revision: Union[str, None] = '14cceaae8253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taboos', sa.Column('taboo_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taboos', 'taboo_code')
    # ### end Alembic commands ###
