"""update modify taboo

Revision ID: cfffda0e6569
Revises: 40c7489b8fac
Create Date: 2025-05-02 04:32:54.751133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfffda0e6569'
down_revision: Union[str, None] = '40c7489b8fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taboos', sa.Column('code', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'taboos', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'taboos', type_='unique')
    op.drop_column('taboos', 'code')
    # ### end Alembic commands ###
