"""update nullable field

Revision ID: d6fe6cf17f6c
Revises: d8a27c078a3b
Create Date: 2025-04-26 01:22:04.170314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6fe6cf17f6c'
down_revision: Union[str, None] = 'd8a27c078a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'subname',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cards', 'text',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('cards', 'real_text',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('cards', 'type_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cards', 'type_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cards', 'faction_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cards', 'faction_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cards', 'alternate_of_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cards', 'alternate_of_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cards', 'pack_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cards', 'pack_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cards', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'is_unique',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cards', 'exceptional',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cards', 'myriad',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cards', 'permanent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cards', 'double_sided',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cards', 'url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cards', 'octgn_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cards', 'flavor',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cards', 'back_flavor',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('cards', 'back_text',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    op.alter_column('cards', 'deck_limit',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'health',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'health_per_investigator',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'sanity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'skill_willpower',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'skill_intellect',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'skill_combat',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'skill_agility',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'skill_wild',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cards', 'real_slot',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('cards', 'illustrator',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cards', 'imagesrc',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('cards', 'backimagesrc',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'backimagesrc',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cards', 'imagesrc',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cards', 'illustrator',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cards', 'real_slot',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cards', 'skill_wild',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'skill_agility',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'skill_combat',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'skill_intellect',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'skill_willpower',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'sanity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'health_per_investigator',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'health',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'deck_limit',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'back_text',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('cards', 'back_flavor',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('cards', 'flavor',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cards', 'octgn_id',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cards', 'url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cards', 'double_sided',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cards', 'permanent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cards', 'myriad',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cards', 'exceptional',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cards', 'is_unique',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cards', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cards', 'pack_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cards', 'pack_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cards', 'alternate_of_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cards', 'alternate_of_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cards', 'faction_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cards', 'faction_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cards', 'type_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('cards', 'type_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cards', 'real_text',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('cards', 'text',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.alter_column('cards', 'subname',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
