"""add field for location and act, agenda card

Revision ID: dc4ebdc6c49a
Revises: 6019b46b9e7d
Create Date: 2025-09-07 03:47:55.445748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4ebdc6c49a'
down_revision: Union[str, None] = '6019b46b9e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('vengeance', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('doom', sa.Integer(), nullable=True))
    op.add_column('cards', sa.Column('clues_fixed', sa.Boolean(), nullable=True))
    op.add_column('cards', sa.Column('stage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'stage')
    op.drop_column('cards', 'clues_fixed')
    op.drop_column('cards', 'doom')
    op.drop_column('cards', 'vengeance')
    # ### end Alembic commands ###
