"""add duplicated field

Revision ID: e98d5c525ac4
Revises: 4df98ec5b9db
Create Date: 2025-05-04 03:22:59.404963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98d5c525ac4'
down_revision: Union[str, None] = '4df98ec5b9db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('duplicated_by', sa.String(length=50), nullable=True))
    op.add_column('cards', sa.Column('alternated_by', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'alternated_by')
    op.drop_column('cards', 'duplicated_by')
    # ### end Alembic commands ###
